ASUWebPlatforms/webspark-ci

- pantheon.upstream.yml
This change could've gone into ./pantheon.yml in the root of the repo (vs. pantheon.upstream.yml), but I wanted to avoid the possible conflicts with end users wanting to customize that file.
> WS2-1627 - File blocking (with 403 errors) to hide files from security scans

- web/profiles/webspark/webspark/webspark.install
When running database updates for 2.9.1 release, an error is thrown for the webspark profile install file due to a missing class declaration "PathautoGeneratorInterface".
Solution: Add the class to the top of the webspark.install file.
- [JIRA ticket](https://asudev.jira.com/browse/WS2-1662)
> WS2-1662: Add missing class for install profile update.

- composer.lock
- web/modules/webspark/webspark_webdir/js/list-field.js
Forgot to change the sort to the new display_last_name prop
This fixes that problem.
To QA this, add "Office of the President" and "ASU Knowledge Enterprise > Biodesign Institute > Biodesign Center for Mechanisms of Evolution > Institute for Mechanism of Cellular Evolution > Leadership" as departments in the "Departments" component.
You will see that Kerry Geiler-Samerotte is now sorted correctly in the GUI listing.
- [JIRA ticket](https://asudev.jira.com/browse/WS2-1618)
> WS2-1618: webspark_webdir: Depts listing people in the admin UI stacked, not in full alphabetical order

- web/modules/webspark/webspark_webdir/config/install/field.field.block_content.web_directory.field_component_type.yml
- web/modules/webspark/webspark_webdir/webspark_webdir.install
This PR adds help text describing how large departments shouldn't use "people" or "people in department", but rather use "departments" or "faculty by rank."
- [JIRA ticket](https://asudev.jira.com/browse/WS2-1610)
> Ws2 1610: Web Directory People and People in Department listings Admin UI doesn't use pager for added profiles

- web/themes/webspark/renovation/renovation.info.yml
I added a new dependency to the renovation theme while working on [This ticket](https://asudev.jira.com/browse/WS2-1615)
This was incorrectly formatted which resulted in a missing dependency warning on the Drupal status page (see screenshots below)
I corrected the naming of the dependency, and confirm that error in UI is now resolved.
- [JIRA ticket bug was introduced on](https://asudev.jira.com/browse/WS2-1615)
Error:
Lack of error:
> correcting asu_brand dependency on renovation theme

- web/modules/webspark/webspark_webdir/webspark_webdir.install
Resolves issue found during spinup of new site - fields removed in update hooks for webdir module get added to new sites.
We need to keep the fields there for sites doing updates that revert settings AND later in update hook 9008 copy the values from the legacy fields to the new fields... So we implement a hook_install() that executes hook 9009 that unlinks the fields.
And to prevent future reverts from bringing the fields back, we also call to hook 9009 in the revert function.
> WS2 release - avoid dupe webdir fields on new sites and future reverts

- web/modules/webspark/asu_react_core/src/Utils/ReactComponentHelperFunctions.php
There are php warnings for asu_react_core module helper functions that result from null values for ranking card, icon settings, and clickable props. Both icon settings and clickable have been removed for components, so we'll need to do some cleanup in the next release. Also, php 8.1 no longer lets null silently convert to an empty string so it needs to be checked then converted.
Solution: Add isset() checks for null.
- Related to [JIRA ticket](https://asudev.jira.com/browse/WS2-1687)
> WS2-1687 - Fix php warning about null values for react helper functions.

- web/modules/webspark/asu_degree_rfi/src/Controller/AsuDegreePagesCreation.php
- web/modules/webspark/asu_degree_rfi/src/Plugin/Block/AsuDegreeRfiDegreeDetailsBlock.php
- web/modules/webspark/asu_degree_rfi/src/Plugin/Block/AsuDegreeRfiDegreeListingBlock.php
_From Michael :_ 
"We need logic in https://github.com/ASUWebPlatforms/webspark-ci/blob/master/web/modules/webspark/asu_degree_rfi/src/Routing/RouteSubscriber.php or
https://github.com/ASUWebPlatforms/webspark-ci/blob/master/web/modules/webspark/asu_degree_rfi/src/Controller/AsuDegreePagesCreation.php so that the “The Degree listing page with nid: could not be found” message only displays when the path matches known degree listing page patterns, otherwise, we should display the WS2 404 page (which looks, as an example, like this: https://search.asu.edu/ljlkjlkjlkj)."
**Solution** : Logic was moved some lines below, so regex first evaluate if the URL is correct, then I validate if it belongs to a degree listing page node.
- [JIRA ticket](https://asudev.jira.com/browse/WS2-1557)
Note: …
> WS2-1557-A: Refactoring the logic to validate if Degree listing page exists

- web/modules/webspark/webspark_blocks/webspark_blocks.install
Multiple revert function calls were removed before update 9017, one of which (9012) created the field_show_borders field, so if a site hasn't been updated in a while (2.7) it will hang on update 9017.
Solution: Add back _webspark_blocks_revert_module_config(); before update 9017
- [JIRA ticket](https://asudev.jira.com/browse/WS2-1704)
> WS2-1704a - Add blocks revert function before update 9017.

- upstream-configuration/scripts/ComposerScripts.php
Adjust how the custom and Webspark patches are merged, in order to preserve custom patches if they use the same key as ours.
> FIX: Adjust how the custom and Webspark patches are merged

- web/modules/webspark/webspark_utility/src/WebsparkUtilityConfigManager.php
- web/modules/webspark/webspark_utility/webspark_utility.services.yml
People are having a hard time updating to WS2 2.10.2 because of the webspark_update_9014. I discovered that the problem here is that the update_config function being used assumes that the config is already in the active configs. However, this may not always be the case.
So, I have added a check to see if it exists in the active configs, and if not, it installs the config instead of updates it.
This solves the problem.
- [JIRA ticket](https://asudev.jira.com/browse/WS2-1737)
> WS2-1737: Fix config update functionality in webspark_utility module

- upstream-configuration/composer.json
Upstream config shouldn't reference itself.
- [JIRA ticket](https://asudev.jira.com/browse/WS2-1741)
> WS2-1741 remove upstream config reference to itself

- web/modules/webspark/webspark_blocks/config/install/image.style.block_image_16_9_lge.yml
- web/modules/webspark/webspark_blocks/config/install/image.style.block_image_16_9_med.yml
- web/modules/webspark/webspark_blocks/config/install/image.style.block_image_16_9_sml.yml
- web/modules/webspark/webspark_blocks/config/install/image.style.block_image_1_1_lge.yml
- web/modules/webspark/webspark_blocks/config/install/image.style.block_image_1_1_med.yml
- web/modules/webspark/webspark_blocks/config/install/image.style.block_image_1_1_sml.yml
- web/modules/webspark/webspark_blocks/config/install/image.style.block_image_lge.yml
- web/modules/webspark/webspark_blocks/config/install/image.style.block_image_med.yml
- web/modules/webspark/webspark_blocks/config/install/image.style.block_image_sml.yml
- web/modules/webspark/webspark_blocks/config/install/image.style.video_poster_image.yml
- web/modules/webspark/webspark_blocks/webspark_blocks.install
**Issue:** It’s not obvious to user that crop bounding box must be clicked on in order to apply cropping, and can be saved regardless.
**Solution:** Reconfigure image styles that include the cropping tool so that they “Scale and crop” to a specific aspect ratio if the cropper is not clicked on before saving.
modified:   web/modules/webspark/webspark_blocks/config/install/image.style.block_image_16_9_lge.yml
modified:   web/modules/webspark/webspark_blocks/config/install/image.style.block_image_16_9_med.yml
modified:   web/modules/webspark/webspark_blocks/config/install/image.style.block_image_16_9_sml.yml
modified:   web/modules/webspark/webspark_blocks/config/install/image.style.block_image_1_1_lge.yml
modified:   web/modules/webspark/webspark_blocks/config/install/image.style.block_image …
> WS2 1688 - configure cropping image styles to crop aspect ratio by default

- web/profiles/webspark/webspark/config/install/fontawesome.settings.yml
Bypass FontAwesome validation to avoid false positive validation failures. Needed for how we've decoupled from FA module with rendering.
Test:
On https://pr-148-webspark-ci.ws.asu.edu/card-arrangement attempt replacing the broken card icon with one of the pictoral numeric icons from the first page of options in the icon picker widget. Shouldn't throw an error.
Also view `/admin/config/content/fontawesome` and verify that the bypass validation is checked.
> ws2-1754 - bypass validation setting in fontawesome.settings.yml

- web/profiles/webspark/webspark/config/install/fontawesome.settings.yml
"regular" non-solid icons account for empty spaces in the picker. We don't load the non-solid icons, so shouldn't have them enabled in the picker. Most are pro-only, and those don't appear in the picker, but enough aren't pro and they try to render but don't. This update prevents them from rendering as blanks in the picker.
> ws2-1754 don't to alow configure regular file icons in widget

- web/modules/webspark/asu_brand/src/AsuBrandHelperFunctions.php
Empty local search values, after code refactor in brand module, broke the "empty" value fallback to the site's domain. This resulted in local search settings defaulting to an empty string.
This PR corrects that by checking for !empty instead.
Test
* At `/admin/config/asu_brand/settings` try various "Local Search URL" settings.
* After changing, clear the cache.
* Perform a search from the header. The domain you configured should show as the local search results on https://search.asu.edu.  If you leave the field blank, the current site's domain should be used.
The local search parameter can be verified by looking at the original site's search form (`url_host` is a hidden field and should match the configuration or default fallback). You can also verify after a search by checking for the …
> WS2-1786 check for not empty to avoid false positives

- upstream-configuration/composer.json
- web/profiles/webspark/webspark/webspark.info.yml
Update the WS2 installation profile to 2.11.0.
> Update Webspark profile version number to 2.11.0

- web/themes/webspark/renovation/templates/system/html.html.twig
After the BS5 migration, there is an extra closing tag for the `<head>`. This PR removes that extra closing tag.
- [JIRA ticket](https://asudev.jira.com/browse/WS2-1807)
> WS2-1807: Remove extra closing head tag

- web/modules/webspark/webspark_webdir/config/install/core.entity_form_display.block_content.web_directory.default.yml
- web/modules/webspark/webspark_webdir/config/install/core.entity_view_display.block_content.web_directory.default.yml
- web/modules/webspark/webspark_webdir/webspark_webdir.install
double fields in the Web Directory UI in Layout Builder from the Support hours. Looks like that’s because adding the new alpha filter, I added an update hook that updated the core.entity_form_display.block_content.web_directory.default.yml and core.entity_view_display.block_content.web_directory.default.yml files and they still have the old fields we removed a few releases back. This is the first update that’s hit those again
We need to pull those fields out of the core.entity_* ymls in webspark_webdir.
Once this builds, we need to manually re-run webspark_webdir update 9012. Because of this headache, this PR is against Dev, and when merged, I'll port that update back to the sprint branch and re-run the update on that environment, too.
- [JIRA …
> WS2-1835 remove old fields form core.entity_* ymls in webspark_webdir

- composer.json
- upstream-configuration/composer.json
Composer builds are failing on sites trying to update to WS2.11, because Bower is down and Composer is unable to pull in Font Awesome from it. 
This PR pulls in Font Awesome from Asset Packagist instead. The new package being pulled in is here: https://asset-packagist.org/package/npm-asset/fortawesome--fontawesome-free 
fortawesome--fontawesome-free is renamed in the root composer.json to "fontawesome" so no code or configuration changes are needed in WS2 when this is switched out.
[- [JIRA ticket](https://asudev.jira.com/browse/WS2-1842)](https://asudev.jira.com/browse/WS2-1842)
Example of error when trying to pull in fontawesome from Bower
> Adjusting composer files to pull in fontawesome from Asset Packagist

- web/modules/webspark/webspark_blocks/config/install/field.field.block_content.video_hero.field_hero_background_color.yml
- web/modules/webspark/webspark_blocks/webspark_blocks.install
Heros that were configured to have white text have lost that configuration with the latest update to 2.11. No code errors were seen in applying the update or update hooks. 
The default value was added to the field_hero_background_color in blocks with type=video_hero.
- [JIRA ticket](https://asudev.jira.com/browse/WS2-1839)
> WS2-1839 - The default value was added to the field_hero_background_color in blocks with type=video_hero.

- web/modules/webspark/webspark_blocks/config/install/field.field.paragraph.card.field_media.yml
- web/modules/webspark/webspark_blocks/config/install/field.field.paragraph.card_degree.field_media.yml
- web/modules/webspark/webspark_blocks/config/install/field.field.paragraph.card_story.field_media.yml
- web/modules/webspark/webspark_blocks/webspark_blocks.install
When adding a new card to an existing layout component there are recommendation text that indicates the image should be 588 x 200 px but when uploading an image that fits that size the image is then forced to crop to a 4x3 ratio size.
Changed description text for field_media in Card, Card Degree, Card Story
- [JIRA ticket](https://asudev.jira.com/browse/WS2-1533)
> WS2-1533 - Changed description text for field_media in Card, Card Degree, Card Story

- web/modules/webspark/webspark_blocks/config/install/field.field.paragraph.card_ranking.field_link.yml
- web/modules/webspark/webspark_blocks/webspark_blocks.install
- [JIRA ticket](https://asudev.jira.com/browse/WS2-1800)
> WS2 1800: Ranking card 'read more' 'Link' field now optional

- web/modules/webspark/webspark_webdir/config/install/field.field.block_content.web_directory.field_asurite_ids.yml
- web/modules/webspark/webspark_webdir/css/directory-field.css
- web/modules/webspark/webspark_webdir/js/asurite-field.js
- web/modules/webspark/webspark_webdir/webspark_webdir.install
- web/modules/webspark/webspark_webdir/webspark_webdir.module
People want to re-order listings done in the 'People' and 'People in Departments' listings. 
Solution: Leverage the native drag-and-drop functionality of jsTree and then rewrite the text field after dragging and dropping has finished.
To test:
1. Log into the PR site and navigate to the Web Directory page
2. Click "Layout" and then click on the pencil icon for either the "People" or "People in Departments" listing block and then click "configure."
3. In the "Profiles" section, test the drag and drop functionality by moving people up or down in the list.
4. Make sure that the "Default sort" option is set to "Sort by order people added"
5. Click the "update" button, and then click the "Save Layout" button in Layout Builder.
6. The directory listing should reflect the order which you created …
> Enable drag-and-drop functionality

- web/modules/webspark/webspark_blocks/webspark_blocks.install
- web/profiles/webspark/webspark/webspark.info.yml
Ran into an issue where we needed to ensure the profile update that installed ckeditor5 ran before the webspark_blocks config import. 
This sets that right by implementing https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Extension%21module.api.php/function/hook_update_dependencies/10
It also corrects an oversight where ckeditor5 isn't installed for new sites.
> Ws2 2 12 0 release fixes

- web/modules/webspark/webspark_ckeditor_plugins/css/websparkglobal.css
Late in the prep for release I discovered the admin toolbar overlaps the sticky ckeditor toolbar when scrolling on node edit forms. This update fixes that. 
Before: if you were on a node edit form and scrolled past the top of the body text area, the WYSIWYG form gets covered over by the admin toolbar
Note: The CSS rules are scoped so they shouldn't interfere with the Layout Builder wysiwyg rules and they shouldn't apply if someone has turned off the admin toolbar. They also adapt to the various modes of the admin toolbar.  The rules are scoped to the `form.node-page-edit-form`. We may find in the future we want to open that up further (as long as we avoid regressing the Layout Builder rules).
Testing:
* Verify that when you scroll on the node edit form, the WYSIWYG editor toolbar remains …
> WS2 2.12.0 release - fix ckeditor toolbar stickiness on node forms

- web/modules/webspark/webspark_cas/src/EventSubscriber/WebSparkCasSubscriber.php
- web/modules/webspark/webspark_cas/src/WebsparkCasServiceProvider.php
- web/modules/webspark/webspark_cas/webspark_cas.services.yml
Problem: The wrong Class was being used, which broke this module's functionality.
Solution: We needed to not only use the correct class, but also to override the Event Subscriber service so that our code fires first. This was done via a new class WebsparkCasServiceProvider which implements the ServiceModifierInterface.
I have removed the code checking for whether it is a forced path, since that is handled by a separate "new" class in the CAS module now. I have also removed the service definition; since we are hijacking the other service, we don't need to load this service with a separate service definition. 
- [JIRA ticket](https://asudev.jira.com/browse/WS2-1877)
> fix webspark_cas module

- web/themes/webspark/renovation/src/sass/layout-builder.scss
Added new styles for layout builder to have compatibility for Drupal 10
- [JIRA ticket](https://asudev.jira.com/browse/WS2-1875)
> WS2-1875: Added new styles for layout builder to have compatibility for Drupal 10

- composer.lock
- upstream-configuration/composer.json
- web/themes/webspark/renovation/css/layout-builder.css
- web/themes/webspark/renovation/includes/theme.inc
- web/themes/webspark/renovation/src/sass/layout-builder.scss
- web/themes/webspark/renovation/templates/form/input--textfield--settings_block_subform_field_icon.html.twig
The FontAwesome iconpicker widget was broken within the off-canvas dialogue due to its style reset that was introduced in Drupal 10.0.0.
The solution was to wrap it in a class that is allowed through the style reset fence. I have also improved some of the CSS so that it is more accessible/legible and pinned the version to a stable release.
> Ws2 1889: JSM - WS2 - Cards, grid links, and anchor menu items with icons (Webspark Test)

- web/modules/webspark/webspark_blocks/src/Form/WebsparkBlocksAdminSettings.php
Webspark blocks admin pageview throws error in watchdog logs.
Remove empty property in the fieldset form element in web/modules/webspark/webspark_blocks/src/Form/WebsparkBlocksAdminSettings.php
- [JIRA ticket](https://asudev.jira.com/browse/WS2-1888)
> WS2-1888: Delete empty property in fieldset and adjust comment spacing.

- upstream-configuration/patches.webspark.json
- web/profiles/webspark/webspark/webspark.info.yml
- web/profiles/webspark/webspark/webspark.install
> WS2-1871: Added hook_update to uninstall ckeditor/fakeobjects module

- web/modules/webspark/asu_brand/asu_brand.module
- web/modules/webspark/asu_brand/src/Plugin/Block/AsuBrandHeaderBlock.php
`component-header` supports multiple headers in a dropdown column, but we didn't have a way to define that on the `asu_brand` module side. 
Adds a `stackable heading` menu item config that is skipped in the navTree prop logic that turns headings into new columns, and then gets converted to the `heading` type after that processing so it's sent to the component with a valid type. This enables stacking of sections with more than one header in a column. 
Edit the main menu used in a header…
1. You will need a drop down with multiple columns.
2. Add a new column using a “Heading - starts a new column” and ensure that works as it did originally. (Testing that we don’t have any regressions).
3. Now change that new column menu item to a “Column break…” item. There should still be a column for …
> Ws2 1486 stackable headings

- composer.json
- composer.lock
- upstream-configuration/composer.json
- web/profiles/webspark/webspark/config/install/editor.editor.basic_html.yml
- web/profiles/webspark/webspark/config/install/editor.editor.full_html.yml
- web/profiles/webspark/webspark/config/install/editor.editor.minimal_format.yml
- web/profiles/webspark/webspark/config/install/filter.format.basic_html.yml
- web/profiles/webspark/webspark/config/install/filter.format.full_html.yml
- web/profiles/webspark/webspark/config/install/filter.format.minimal_format.yml
- web/profiles/webspark/webspark/webspark.install
Update text formats; install editor_advanced_link module; uninstall CKEditor4 and Fakeobjects modules.
- [JIRA ticket](https://asudev.jira.com/browse/WS2-1871)
> Ws2 1871: Clean up CKEditor required packages

- web/sites/default/default.robots.txt
We need to keep our reference "site owner managed files" in sync with D10 references. Most are not included in our repo and get built out by scaffolding and/or composer, but the default.robots.txt is one we provide. So updating it here to match https://git.drupalcode.org/project/drupal/-/blob/10.2.2/robots.txt?ref_type=tags
- [JIRA ticket](https://asudev.jira.com/browse/WS2-1727)
> WS2-1727 sync default.robots.txt

- web/profiles/webspark/webspark/webspark.info.yml
Install process throws an error because color, quickedit and rdf are no longer in the codebase but included in the profile's .info.yml
Solution: remove them.
> WS2 release don't try to install color, quickedit, rdf

- web/themes/webspark/renovation/src/sass/base/_drupal.scss
Regression: Small space below header has returned
Changed css selector in _drupal.scss from '.page-wrapper-web-spark main' to '.page-wrapper-webspark:first-child'
- [JIRA ticket](https://asudev.jira.com/browse/WS2-1867)
> WS2-1867: Changed css selector in _drupal.scss from .page-wrapper-web-spark main to .page-wrapper-webspark:first-child

- composer.lock
- upstream-configuration/composer.json
- upstream-configuration/patches.webspark.json
I have created a fix and submitted it to Drupal.org. It builds off of the dev branch. In order to keep our site as stable as possible while on the dev branch, I have chosen to pin us to a specific commit, which is the current top commit of that branch. If more commits are made, Composer will ignore them. This will keep us stable until we can vet the new commits and eventually update to a stable version of the module.
- [JIRA ticket](https://asudev.jira.com/browse/WS2-1907)
> WS2-1907: Fontawesome icons are doubled up in the icon picker widget. Needs fix.

- features/section-options.feature
This one should be pretty straight-forward. It checks for the layouts from core that we don't want. So, if you run it in an environment that hasn't had that update, it will fail. But, otherwise, it should work well.
> WS2-1817: Verify layout section options and each option's column width options

- web/profiles/webspark/webspark/config/install/core.entity_view_display.node.page.default.yml
- web/profiles/webspark/webspark/webspark.install
It looks like the yaml file just has stuff moved around. I figured I'd update it just in case there were any other things D10 changed. So, really, the only change in this PR is in the `.install` file's hooks. Pretty straightforward.
P.S. Since Dev already has run `hook_update_10000` this won't change anything in the CI build. But, when people apply the updates for the first time, it will take effect. A quick QA check would be to run:
`terminus drush webspark-ci.pr-301 -- ev "\Drupal::service('update.update_hook_registry')->setInstalledVersion('webspark', 9018)"; terminus drush webspark-ci.pr-301 -- updb` which should run the hook.
P.P.S. I have run the above terminus commands in the PR multidev. It's easy to test this by opening a Basic Page (like the Accordion page) and attempting to add …
> add hook_update to remove unwanted layouts

- web/themes/webspark/renovation/src/sass/helpers/_ckeditor.scss
The button text color is off while using the ckeditor in tabbed content. 
Added new classes for ckeditor buttons used into tab content
- [JIRA ticket](https://asudev.jira.com/browse/WS2-1921)
> WS2-1921: Added new classes for ckeditor buttons used into tab content

- web/modules/webspark/webspark_webdir/src/Plugin/Field/FieldWidget/WebdirAddPeopleWidget.php
- web/modules/webspark/webspark_webdir/src/Plugin/Field/FieldWidget/WebdirAddWidget.php
- web/modules/webspark/webspark_webdir/src/Plugin/Field/FieldWidget/WebdirAsuriteWidget.php
- web/modules/webspark/webspark_webdir/src/Plugin/Field/FieldWidget/WebdirCampusWidget.php
- web/modules/webspark/webspark_webdir/src/Plugin/Field/FieldWidget/WebdirDepartmentsWidget.php
- web/modules/webspark/webspark_webdir/src/Plugin/Field/FieldWidget/WebdirEmployeeTypeWidget.php
- web/modules/webspark/webspark_webdir/src/Plugin/Field/FieldWidget/WebdirExpertiseWidget.php
- web/modules/webspark/webspark_webdir/src/Plugin/Field/FieldWidget/WebdirListWidget.php
Adding the class `.ck-reset` allows items through the style fence.
Testing steps:
- Go to `/node/31/layout`
- Click the pencil icon to load the "off canvas" dialog for each web directory block
- Make sure that there are checkboxes and collapsible triangles in the "Departments," "Filter by campus," "Filter by expertise areas," and "Filter by employee type" collapsibles
- Make sure that names in the "add profiles" section have collapsible triangles
- Make sure that the names in the "Profiles" section have multi-directional arrows and can be drag-dropped
- Make sure that none of these have list item bullets. They should be "bullet-less"
If all of these things are the case, it passes.
> allow jstree through style fence

- web/modules/webspark/webspark_blocks/webspark_blocks.info.yml
- web/modules/webspark/webspark_utility/config/install/filter.format.basic_html.yml
- web/modules/webspark/webspark_utility/config/install/filter.format.full_html.yml
- web/modules/webspark/webspark_utility/config/install/filter.format.restricted_html.yml
New site creation was running into missing dependencies errors from paragraph fields for ranking cards when `webspark_blocks` tried to load. We can't include those ymls in `webspark_blocks` because they're in the profile and also that would make the config readonly. Additionally, we can't declare the profile as a dependency, because the profile depends on `webspark_blocks`. Circularity!
Solution: I sanitized the needed filter.format.*.yml files of additional dependencies, and put them into `webspark_utilities` which is declared as a dependency in `webspark_blocks`. That dependency needed to be cleaned up since we no longer pull the module in using Composer, and then I also added a dependency on the drupal:filter module. Now, those formats get pulled in an satisfied for `webspark_blocks` …
> WS2-1939 fix circular dependency issue using webspark_utilities

- web/profiles/webspark/webspark/webspark.install
This is a tough one to test. My approach has been to hopefully do the find-replace before any of the other Drupal 10 configs get changed. I have been able to verify the functionality by copy and pasting the code I added here into existing Drupal 9 sites that are on WS 2.11.1. To check that it is working, I spun up the site, and then exported the configs (with `ddev drush cex`) and committed them temporarily to git, so that I could see future changes. Then I ran `ddev drush updb` and after the update finished, I ran `ddev drush cex` again. This allowed me to easily see if any config files had been changed. I then verified visually within a few of the files to see if they had been created properly. I also did a search within the `config` directory in my IDE to see if there were any …
> add hook to remove 'node_type' in configs

- web/modules/webspark/webspark_blocks/src/Form/WebsparkBlocksAdminSettings.php
- web/modules/webspark/webspark_blocks/webspark_blocks.module
Webspark blocks admin pageview throws error in watchdog logs.
Second fix for this ticket -- add checks for default settings for links, makes both fields require each other before saving (field states) and checks if there are any links before displaying related links title.
- [JIRA ticket](https://asudev.jira.com/browse/WS2-1888)
> WS2-1888 - Fix webspark blocks 404 settings and related links display

- features/fontawesome.feature
@mlsamuelson Sorry to re-open this PR.
I realized that I wasn't doing cleanup after adding the twitter icon and saving it. So, the page will end up having a bunch of twitter icons, one for every time we run the test. 
Since we are already testing that icons display in the "View" page, I figured it would be best to just remove lines 59-63.
> Ws2 1949 - update

- web/modules/webspark/webspark_blocks/js/anchor-menu.js
Also fixed issue where page reloads were not attaching anchor menu when page reloaded in scrolled state
- [JIRA ticket](https://asudev.jira.com/browse/WS2-1961?atlOrigin=eyJpIjoiNGYxZWJjNjA5ZmRlNGExNmEwM2JiZDkxZDYxMTdlNjIiLCJwIjoiaiJ9)
> Fixed anchor menu issue where it was detaching too soon on scroll up

- web/themes/webspark/renovation/package.json
- web/themes/webspark/renovation/yarn.lock
Fix mixed lists styles by updating to latest theme.
We need to verify that Accordions, card padding and endorsed logos in footer aren't negatively impacted - details on https://asudev.jira.com/browse/WS2-1984?focusedCommentId=1951183 (these are fixes from the intermediate releases and in some cases may require additional development in WS2 to accommodate them).
> WS2-1984 update uds theme to 1.9.6 for mixed lists fix

- upstream-configuration/patches.webspark.json
- web/modules/webspark/webspark_ckeditor_plugins/webspark_ckeditor_plugins.ckeditor5.yml
- web/modules/webspark/webspark_ckeditor_plugins/webspark_ckeditor_plugins.install
- web/profiles/webspark/webspark/webspark.install
This patch solved the content adding after injecting the element, but it's not resolving the switching between FULL & BASIC HTML. Also, it strip the classes when clicking on Source and edit the content.
It's a quick solution that could give us sometime.
> WS2-1983: applying a patch to add content after injecting the grid.

- web/modules/webspark/webspark_blocks/webspark_blocks.module
Php 8 is more strictly typed than previously, so if code expects an array (in a foreach, for example) and gets NULL, it throws a "warning." Adding a conditional prior to the foreach solves this problem.
- [JIRA ticket](https://asudev.jira.com/browse/WS2-1995)
> WS2 1995: Null warning on every page needs to be fixed

- web/modules/webspark/webspark_module_renovation_layouts/layouts/fourcol_fixed_width_section/fourcol-fixed-width-section.html.twig
- web/modules/webspark/webspark_module_renovation_layouts/layouts/onecol_article_hero_section/onecol-article-hero-section.html.twig
- web/modules/webspark/webspark_module_renovation_layouts/layouts/onecol_fixed_width_section/onecol-fixed-width-section.html.twig
- web/modules/webspark/webspark_module_renovation_layouts/layouts/onecol_full_width_section/onecol-full-width-section.html.twig
- web/modules/webspark/webspark_module_renovation_layouts/layouts/threecol_fixed_width_section/threecol-fixed-width-section.html.twig
- web/modules/webspark/webspark_module_renovation_layouts/layouts/twocol_bootstrap_section/layout--twocol-bootstrap-section.html.twig
- web/modules/webspark/webspark_module_renovation_layouts/webspark_module_renovation_layouts.module
- web/themes/webspark/renovation/package.json
- web/themes/webspark/renovation/src/components/node/node.twig
- web/themes/webspark/renovation/src/sass/nodes/_node.scss
- web/themes/webspark/renovation/templates/content/node--degree-detail-page.html.twig
- web/themes/webspark/renovation/templates/content/node--degree-listing-page.html.twig
- web/themes/webspark/renovation/templates/page/page.html.twig
- web/themes/webspark/renovation/templates/views/views-view--page.html.twig
This PR updates several twig theme files in order to enforce a white background on nearly all content that is generated by tools provided in Webspark. Primarily, we do this by making content types and Layout Builder sections have the `bg-white` Bootstrap5 class.
The white background change disrupted the existing pink background used to indicate unpublished content. So, I have re-implemented that in a more robust way, by applying the pink background to the page instead of the node template. To accomplish this, I have added a preprocess function that adds a new globally available variable, "is_published." This can be accessed by any twig template, and be used as needed.
QA Test steps:
- Log in to the site as an admin
- Open the Inspector tool and add the style `background-color: red` to the …
> WS2-1656: Background Colors - Some components do not have default background colors

- web/themes/webspark/renovation/src/components/tabbed-panels/tabbed-panels.js
- web/themes/webspark/renovation/src/components/tabbed-panels/tabbed-panels.twig
Accessibility fixes that hadn't happened yet were for horizontal tab browsing via the keyboard was not using `scrollIntoView`, which is in UDS, so I have added it. Also, WCAG indicates that we need to add `tabindex="0"` to each tab panel's content area for accessibility. So, I have added that as well.
QA Steps:
- Navigate to /tabbed-content
- After the page loads, hit Tab on the keyboard. It should highlight a link that says “Skip to main content.” Press Enter.
- Press Tab again, and the first tab should receive the focus.
- Use keyboard left/right/up/down arrows to navigate between tabs. 
- As you get to the edge of visible tabs, it should scroll to reveal more tabs.
- When you get to the last tab, it should “loop around” and focus on the first tab and scroll to it.
- From one of the …
> Ws2 2004: Accessibility QA: Profile Edit UI - Tabs

- web/themes/webspark/renovation/templates/form/fieldset.html.twig
When you use the radio element on webforms and set it to required, the red ‘required asterisk’ don’t show up for the end user
Added required classes for fieldset in Webforms radios
- [JIRA ticket](https://asudev.jira.com/browse/WS2-1744)
> WS2-1744: JSM - WS2 - Webform (Barrett Student)

- web/profiles/webspark/webspark/config/install/system.performance.yml
- web/profiles/webspark/webspark/webspark.install
Cache TTL best practices for Pantheon aren't in place.
Set page cache max_age to 3600 seconds (1 hr).
To test:
1. Check that the cache max age settings on the admin performance page is set to 1 hour after this update is applied.
2. With a newly created site, verify that the cache max age is set to 1 hour.
- [JIRA ticket](https://asudev.jira.com/browse/WS2-2011)
> WS2-2011 add max_age caching config for install and update

- web/themes/webspark/renovation/src/components/tabbed-panels/tabbed-panels.js
The current Tabbed Panels implementation on the WS2 side is faulty
Added new check for nav scrollWidth to not render next button on tabs
- [JIRA ticket](https://asudev.jira.com/browse/WS2-2016)
> WS2-2016: Tabbed Panels

- README.md
- web/themes/webspark/renovation/templates/block/block--inline-block--accordion.html.twig
- web/themes/webspark/renovation/templates/block/block--inline-block--blockquote.html.twig
- web/themes/webspark/renovation/templates/block/block--inline-block--card-and-image.html.twig
- web/themes/webspark/renovation/templates/block/block--inline-block--card-arrangement.html.twig
- web/themes/webspark/renovation/templates/block/block--inline-block--card-carousel.html.twig
- web/themes/webspark/renovation/templates/block/block--inline-block--card-image-and-content.html.twig
- web/themes/webspark/renovation/templates/block/block--inline-block--carousel-image.html.twig
- web/themes/webspark/renovation/templates/block/block--inline-block--content-image.html.twig
- web/themes/webspark/renovation/templates/block/block--inline-block--gallery.html.twig
- web/themes/webspark/renovation/templates/block/block--inline-block--image-and-text-block.html.twig
- web/themes/webspark/renovation/templates/block/block--inline-block--image-background-with-cta.html.twig
- web/themes/webspark/renovation/templates/block/block--inline-block--inset-box.html.twig
- web/themes/webspark/renovation/templates/block/block--inline-block--news.html.twig
- web/themes/webspark/renovation/templates/block/block--inline-block--tabbed-content.html.twig
- web/themes/webspark/renovation/templates/block/block--inline-block--testimonial-on-image-background.html.twig
- web/themes/webspark/renovation/templates/block/block--inline-block--testimonial.html.twig
- web/themes/webspark/renovation/templates/block/block--inline-block--text-content.html.twig
- web/themes/webspark/renovation/templates/block/block--inline-block--video.html.twig
- web/themes/webspark/renovation/templates/block/block--inline-block--webform.html.twig
Currently, when clicking a link for the Anchor Menu, the page will scroll to the block, but the Anchor Menu will cover the block's title if it is visible. This PR normalizes the location of the Anchor Menu target markup in block templates, so that the target is now the first element in the block.
- [JIRA ticket](https://asudev.jira.com/browse/WS2-1876)
- Solution is documented on the Jira ticket
- QA steps to verify have been included on the Jira ticket
- No new PHP or JS errors
- No accessibility issues are introduced with this update
- Chrome
> WS2-1876: Normalize the location of the Anchor Menu targets markup

- web/modules/webspark/asu_brand/css/asu_brand.header.css
Drupal 10 appears to have changed some CSS so that the admin toolbar is no longer fixed on mobile. This PR adds a simple CSS rule to keep the toolbar fixed at all times. This is not targeting mobile only because our header is also fixed at all times.
- [JIRA ticket](https://asudev.jira.com/browse/WS2-2021)
- Solution is documented on the Jira ticket
- QA steps to verify have been included on the Jira ticket
- No new PHP or JS errors
- No accessibility issues are introduced with this update
- Chrome
> WS2-2021: Keep the toolbar fixed at all times

- composer.lock
- upstream-configuration/composer.json
Need a update of Drush version to avoid error caused by webflo/drupal-finder
Update Drush version to avoid error caused by webflo/drupal-finder
- [JIRA ticket](https://asudev.jira.com/browse/WS2-2059)
> WS2-2059: Update Drush version to avoid error caused by webflo/drupal-finder

- web/modules/webspark/asu_brand/js/asu_brand.header.js
- web/modules/webspark/asu_brand/src/Plugin/Block/AsuBrandHeaderBlock.php
Added new check in asu_brand_header.js if user is admin or not
- [JIRA ticket](https://asudev.jira.com/browse/WS2-2075)
> WS2-2075: Added new check in asu_brand_header.js if user is admin or not

- web/modules/webspark/webspark_blocks/config/install/field.field.block_content.content_image.field_media.yml
- web/modules/webspark/webspark_blocks/webspark_blocks.install
As a user of the content image overlap block, if you use a 4:3 aspect ratio the image sizes crop correctly.  If you use the Cropped image square (1:1), Cropped image wide (16:9), or image, (see below screen shot) the image gets cut off on the output.
Remove the crop options  (1:1, image and 16:9)
- [JIRA ticket](https://asudev.jira.com/browse/WS2-2035)
> WS2-2035: Removing crop options (1:1, image and 16:9) from content image overlap block.

- upstream-configuration/patches.webspark.json
- web/themes/webspark/renovation/templates/paragraphs/paragraph--cta.html.twig
I was able to determine that there were two problems with the commit Dave mentioned. One problem is that the patch didn’t work as expected. However, the patch is not what caused the problem. In fact, the problem was caused by this commit to Drupal core: https://git.drupalcode.org/project/drupal/-/commit/7dcd798ed943910e37cfe264dd1a7998ce1e1ac8
That commit is associated with the following bug ticket: https://www.drupal.org/project/drupal/issues/2885351
Since it was committed, other tickets have sprung up pointing out the issue Dave mentioned above. Two of these are: https://www.drupal.org/project/link_attributes/issues/3423171 and [https://www.drupal.org/project/drupal/issues/3423031](https://www.drupal.org/project/drupal/issues/3423031#comment-15460860). Both of these tickets recommend …
> Ws2 2071: Fix Call to Action button regression

- web/modules/webspark/webspark_blocks/js/anchor-menu.js
Anchor Menu links do not properly highlight the active area
Removed Bootstrap scrollspy from anchor-menu.js and I added a new custom functionality
- [JIRA ticket](https://asudev.jira.com/browse/WS2-2029)
> WS2-2029: Anchor Menu links do not properly highlight the active area

- web/modules/webspark/webspark_blocks/config/install/field.field.block_content.grid_links.field_links_color.yml
- web/modules/webspark/webspark_blocks/config/install/field.field.block_content.testimonial.field_accent_color.yml
- web/modules/webspark/webspark_blocks/config/install/field.field.block_content.testimonial_on_image_background.field_accent_color.yml
- web/modules/webspark/webspark_blocks/config/install/field.storage.block_content.field_accent_color.yml
- web/modules/webspark/webspark_blocks/config/install/field.storage.block_content.field_card_arrangement_display.yml
- web/modules/webspark/webspark_blocks/config/install/field.storage.block_content.field_links_color.yml
- web/modules/webspark/webspark_blocks/config/install/field.storage.paragraph.field_accent_color.yml
- web/modules/webspark/webspark_blocks/config/install/field.storage.paragraph.field_citation_style.yml
- web/modules/webspark/webspark_blocks/webspark_blocks.install
- web/modules/webspark/webspark_blocks/webspark_blocks.module
Modified default values like '' or ' ' in List(Text) fields
- [JIRA ticket](https://asudev.jira.com/browse/WS2-1934)
> WS2-1934: Modified default values like '' or ' ' in List(Text) fields

- composer.lock
- upstream-configuration/composer.json
This PR adds the SMTP Authentication module to Webspark. By default, the module will not be activated.
- [JIRA ticket](https://asudev.jira.com/browse/WS2-2008)
> WS2-2008: Add the SMTP Authentication module

- web/profiles/webspark/webspark/modules/webspark_installer_forms/src/Form/WebsparkConfigureHeaderForm.php
**WS2-1936 (PR 464) unblocks this PR and must be merged before merging this PR**
During WS2 spin up/site config, Parent unit name and Parent Department URL fields are optional, but become required (asterisk appears) when user enters one of the values. This is intended functionality because one depends on the other, however, it might need some enhancement so users know if one field is populated, both fields become required.
Make Parent Department URL field only display when Parent unit name field is populated.
- [JIRA ticket](https://asudev.jira.com/browse/WS2-1676)
> WS2-1676: Site spin up/config - Parent unit info fields UI clarification

- web/themes/webspark/renovation/css/ckeditor-override.css
The visual editor in the body displays hyperlinks as blue.
Create a new css rule to override the hyperlink color.
- [JIRA ticket](https://asudev.jira.com/browse/WS2-2070)
> WS2-2070: Fixing anchor color for ckeditor (change it to maroon).

- web/profiles/webspark/webspark/webspark.install
Fix missing lock found as part of release prep.
Was accidentally dropped form here: https://github.com/ASUWebPlatforms/webspark-ci/pull/451/files
> WS2-2088 fix missing config lock after update

- web/modules/webspark/webspark_utility/webspark_utility.module
This PR adds some text to the add and edit forms for Basic Pages to promote the use of the Layout Builder.
- [JIRA ticket](https://asudev.jira.com/browse/WS2-1709)
> WS2-1709: Add text to Basic Page admin forms to promote the use of Layout Builder

- web/themes/webspark/renovation/src/components/form-fields/_form-fields.scss
This PR fixes a regression in the submit button for Webforms.
- [JIRA ticket](https://asudev.jira.com/browse/WS2-2142)
> WS2-2142: Fix Webform submit button padding

- web/modules/webspark/asu_brand/src/Plugin/Block/AsuBrandHeaderBlock.php
- web/profiles/webspark/webspark/modules/webspark_installer_forms/src/Form/WebsparkConfigureHeaderForm.php
Make Parent department URL field hidden unless Parent unit name field is filled on both site spin-up and ASU header block configuration forms. If Parent unit name field is filled, also make the Parent department URL field required, and visa versa. 
- [JIRA ticket](https://asudev.jira.com/browse/WS2-2130)
> WS2-2130-hotfix: update Parent unit fields in spin up and header block

- web/themes/webspark/renovation/templates/page/page.html.twig
This PR removes the `tabindex="-1"` from the main content area.
- [JIRA ticket](https://asudev.jira.com/browse/WS2-2145)
> WS2-2415: Remove the tabindex from the main content element

- web/themes/webspark/renovation/package.json
- web/themes/webspark/renovation/yarn.lock
update unity theme for blue text on IOS
- [JIRA ticket](https://asudev.jira.com/browse/WS2-2146?atlOrigin=eyJpIjoiNTg5OTNhOWM4ZjM4NDA1MDg5ODc4NGQ2NzVjZjg2NTEiLCJwIjoiaiJ9)
> WS2-2141: update unity theme for blue text on IOS

- composer.lock
- upstream-configuration/composer.json
UPDATE on the [polyfill.io](http://polyfill.io/) issue: Further digging has identified that the Drupal contrib module Webform 6.2.2, included in Webspark 2 declares [polyfill.io](http://polyfill.io/) as a library. The threat is addressed at this time by domain registrar having taken down that domain. It now serves nothing. In the upcoming Webspark 2.13.0 release, we are updating to the newest Webform version (6.2.3) which avoids that dependency. 
Update in composer require and include updated lock file in the commit for the webform module.
- [JIRA ticket](https://asudev.jira.com/browse/WS2-2165)
> WS2-2165: Update to Webform 6.2.3 module bc polyfill.io

- web/themes/webspark/renovation/src/components/tabbed-panels/tabbed-panels.js
Removed innerWidth check in tabbed-panels.js
- [JIRA ticket](https://asudev.jira.com/browse/WS2-2150)
> WS2-2150: Removed innerWidth check in tabbed-panels.js

- web/modules/webspark/asu_degree_rfi/src/Controller/AsuDegreePagesCreation.php
Fixes blocker to EFI-148 testing. Regression in degree pages creation. Was failing for anonymous users. 
Steps to Test:
1. verify the degree page doesn't exist in the site
2. as anonymous, click the link to that degree in a degree listing page.
3. verify the degree detail page loads
4. Also conduct steps 1-3 as a logged in user to ensure there is no regression in the other direction.
5. check the db logs. No errors should have been generated by the above actions.
6. Try creating a bogus plancode and use it in a degree URL... no page should get created for that fake degree and a message to that effect should display. The RFI form may display, and that's okay and out of scope here.
7. Try editing the plancode of a degree page to set it to a fake plancode. Save and view the degree page. The …
> Degree pages issue

- web/profiles/webspark/webspark/config/install/field.field.block_content.image.field_image_caption.yml
- web/profiles/webspark/webspark/webspark.install
- web/themes/webspark/renovation/src/components/block/image-block.twig
- web/themes/webspark/renovation/src/components/image/_images.scss
- web/themes/webspark/renovation/src/sass/layout-builder.scss
I have adjusted the CSS to apply the drop shadow to the image itself. This solves the problem. I also have added a border to the top of the caption box, a shadow to the caption, and a margin between the image and the caption box.
QA: 
- Check if the rounded image has a drop shadow that does not go outside the image itself.
- In the edit form, the caption field should have help text that indicates that captions will not display for rounded images.
- Set a caption in the edit form and verify that it does not display
- Make sure that existing drop shadows on rectangular images still display correctly (no regressions)
- [JIRA ticket](https://asudev.jira.com/browse/WS2-2143)
> fix drop shadow on captions

- upstream-configuration/patches.webspark.json
Currently, when users use the add media button from the CKE toolbar, after choosing an image the focus automatically shifts to the save button for the content. This is disruptive (especially on long pages) as the user will need to scroll back to their last position to continue editing content. 
This PR applies a patch to ensure that after the media is added, the focus shifts to the media itself.
- [JIRA ticket](https://asudev.jira.com/browse/WS2-2106)
> WS2-2106: Add patch to apply fix for insert media dialog focus

- web/themes/webspark/renovation/src/components/sidebar/sidebar.twig
Refactoring sidebar.twig changed h2 to h3
- [JIRA ticket](https://asudev.jira.com/browse/WS2-1753)
> WS2-1753: JSM - WS2 - Sidebar menu (Brandguide)

- web/themes/webspark/renovation/src/components/buttons/button-action.twig
A11y role=“link” is not needed as <a> role is already a link
- [JIRA ticket](https://asudev.jira.com/browse/uds-1683)
> Remove role=“link” from a tag

- web/themes/webspark/renovation/src/sass/layout-builder.scss
The Layout Builder form actions buttons currently go below the content of hero images.
We need to increase the z-index value so that the form actions buttons are above the hero image content.
QA Steps:
- Log and navigate to the Kitchen Sink page
- Click on the “Layout” tab to load layout builder
- Scroll past the hero image. If the buttons now display above the hero content (text, background shadow, and buttons), then this passes.
- [JIRA ticket](https://asudev.jira.com/browse/WS2-2175)
> WS2-2175: Fix layout builder .form-actions z-index to be above hero content

- web/modules/webspark/asu_brand/src/Plugin/Block/AsuBrandHeaderBlock.php
This PR makes the "Site URL" field found in the ASU Brand Header block settings optional, and makes a small change to the fields' description.
Currently, the field is required, but the user does not manually input the URL during the site creation process. The URL is automatically set to the current sites' domain. This becomes a problem for sites that do not have a parent unit because it is common for the site to be built on the DEV or TEST environment, and this current process will save that environments' domain in the configs. After the site is launched LIVE, the user must remember to manually update the URL in this field to the new URL.
- [JIRA ticket](https://asudev.jira.com/browse/WS2-1707)
> WS2-1707: Update the Site URL field to be optional

- web/modules/webspark/webspark_blocks/js/anchor-menu.js
- web/modules/webspark/webspark_blocks/templates/webspark-blocks-anchor-menu.html.twig
Changed h4 to h2 on anchor-menu and added js
- [JIRA ticket](https://asudev.jira.com/browse/WS2-2200)
> WS2-2200: Changed h4 to h2 on anchor-menu and added js

- web/modules/webspark/webspark_utility/src/Routing/RouteSubscriber.php
- web/modules/webspark/webspark_utility/webspark_utility.services.yml
This PR adds a route subscriber to remove access to the `update.module_install` route.
- [JIRA ticket](https://asudev.jira.com/browse/WS2-2214)
> WS2-2214: Remove the "Add new module" button

- web/modules/webspark/webspark_webdir/js/asurite-field.js
The big work for this ticket has to be done in SCHWEB. It is in [SCHWEB-1275](https://asudev.jira.com/browse/SCHWEB-1275). This pull request only fixes the logic to remove the extra commas if no display name, title, or department is provided. This will make for a more sustainable interface, regardless of whether some data exists for display.
QA Steps:
- Navigate to /node/31/layout and click the pencil icon to open the Off Canvas dialog for the “People” section.
- Under “Profiles” you should see a list of the profiles that have been selected for display. They should display as the following:
- asurite id, display name, department name, title. If any of those items are missing, you should not see a trailing comma.
- If this is the case, it passes.
- [JIRA …
> WS2-2154: Update People Results in the Webdir admin UI

- upstream-configuration/.gitignore
- upstream-configuration/patches.webspark.json
- upstream-configuration/patches/fix_inline_icons_1.patch
All fontawesome icons in ckeditor are adding an extra space so that when a link is added to the icon, it has an underline right after it.
Travis discovered that the `&nbsp;` problem was stemming from a patch of the fontawesome module that Juan Pablo created. The following are the steps that fixed the issue:
- reroll patch to remove the extra `&nbsp;`
- put new patch in a new directory called `patches` within `custom-dependencies`
- whitelist new patches folder in git ignore file
- add patch to `patches.webspark.json` file in `upstream-configuration`
- run composer update
QA Steps:
- visit https://pr-550-webspark-ci.ws.asu.edu
- create new content
- Add a text content block
- add a fontawesome icon
- add a link to the fontawesome icon
- verify there is no underline following the linked …
> WS2-2170: new inline icon fix

- web/modules/webspark/webspark_utility/src/Drush/Commands/WebsparkUtilityCommands.php
The login checking was insufficient and not catching things. I have updated it so that it works more reliably.
QA steps:
1. Pull this branch to your local machine and create a DDEV container (if you don't already have one)
2. Make sure that you are not logged into terminus within DDEV. To to this, run `ddev ssh` and then run `terminus auth:logout` and then exit from the ssh session
3. Run the drush command: `ddev drush wcr`
4. The command should sense that you aren't logged in and should provide an error message in the terminal that says:
```
[error]  Your DDEV instance is currently not logged in to Pantheon via terminus.
Please run `ddev ssh` and then run `terminus auth:login --machine-token=$TERMINUS_MACHINE_TOKEN; exit` to authenticate.
```
5. If the error shows up, this passes.
- …
> WS2-2269: Fix error checking on the Webspark Config Refresh drush command

- web/profiles/webspark/webspark/config/install/field.field.paragraph.image_based_card.field_link.yml
- web/profiles/webspark/webspark/webspark.install
This PR makes the link text in Image Based Cards required. It also adds help text.
- [JIRA ticket](https://asudev.jira.com/browse/WS2-2260)
> WS2-2260: Make button text required for Image Based cards

- web/modules/webspark/webspark_blocks/js/anchor-menu.js
The anchor menu duplicates in the sticky menu after every anchor menu update inside layout builder admin.
QA Steps:
- navigate to https://pr-544-webspark-ci.ws.asu.edu/anchor-menu
- navigate to edit in layout builder
- create a new block, + Create content block, and create a Text Content block
- after adding block admin title and some formatted text, under Appearance Settings, create an Anchor menu title and select an icon for it, and finally click Add block
- Check that the newly created Anchor menu item has been added and that the entire anchor menu isn't being duplicated
- Attempt drag and dropping the associated Anchor content to another place on the page to make sure the Anchor menu resorts items appropriately 
- Save layout and make sure anchor menu functions as expected
- [JIRA …
> WS2-2171: Anchor menu duplication in sticky menu after every update inside admin

- web/modules/webspark/webspark_blocks/webspark_blocks.module
- web/themes/webspark/renovation/templates/paragraphs/paragraph--hover-card.html.twig
In further testing of the new Hover Cards block, I noticed the wrong image was being loaded. This PR adds a hook to load the correct (cropped) image.
- [JIRA ticket](https://asudev.jira.com/browse/WS2-2278)
- Create a Basic Page and add a Hover Card block via the Layout Builder
- Ensure that the image used for the block on the front end is the cropped image, and not the original image
> WS2-2278: Load the correct image size for the component

- web/modules/webspark/webspark_module_views_pager/templates/asu-pager-nav.html.twig
- web/modules/webspark/webspark_module_views_pager/templates/asu-pager.html.twig
- web/modules/webspark/webspark_module_views_pager/webspark_module_views_pager.module
On mobile, if the pagination is large enough that the user has to use the horizontal scrolling, the pagination does not always display correctly. Sometimes on page load, the active page is not visible in the pagination, and other times the active page pagination item is cut off the pagination container.
Add functionality to differentiate mobile pagination limit
- [JIRA ticket](https://asudev.jira.com/browse/WS2-2153)
> WS2-2153: Pagination: Mobile positioning not always correct

- web/modules/webspark/webspark_utility/config/install/field.storage.block_content.field_heading.yml
Dependency that's unneeded crept back into yaml and caused error in the install:
```
Drupal\Core\Config\UnmetDependenciesException::create('webspark_utility', Array) (Line: 527)
Drupal\Core\Config\ConfigInstaller->checkConfigurationToInstall('module', 'webspark_utility') (Line: 132)
Drupal\Core\ProxyClass\Config\ConfigInstaller->checkConfigurationToInstall('module', 'webspark_utility') (Line: 206)
Drupal\Core\Extension\ModuleInstaller->install(Array, ) (Line: 83)
Drupal\Core\ProxyClass\Extension\ModuleInstaller->install(Array, ) (Line: 1909)
_install_module_batch('webspark_utility', 'WebsSpark Utility', Array) (Line: 296)
_batch_process() (Line: 187)
_batch_progress_page() (Line: 87)
_batch_page(Object) (Line: 673)
install_run_task(Array, Array) (Line: 578)
install_run_tasks(Array, NULL) …
```
> WS2 release - remove unmet and unneeded dependency

- web/themes/webspark/renovation/src/components/blockquote/_blockquote.scss
Changed h2 color on blockquote animated
- [JIRA ticket](https://asudev.jira.com/browse/WS2-2348)
> WS2-2348 : Changed h2 color on blockquote animated

- web/themes/webspark/renovation/src/components/cards/card-arrangement.twig
Added if to check empty Heading
1. Create or edit a Basic Page.
2. Add or edit a Card Arrangement in the Layout section.
3. In the Main Content panel, leave the Heading field blank.
4. Inspect the final result and confirm that the empty `<h2>` tag has disappeared.
- [JIRA ticket](https://asudev.jira.com/browse/WS2-2290)
> WS2-2290: Added if to check empty Heading

- web/themes/webspark/renovation/src/components/headings/heading.twig
Added a condition to remove `tabindex="0"` from `<h1>` headings.
- [JIRA ticket](https://asudev.jira.com/browse/WS2-2297)
> WS2-2297: All Custom Blocks: H1 heading text is focusable, but shouldn't be

- web/themes/webspark/renovation/src/components/quote-image-background/quote-image-background.twig
- web/themes/webspark/renovation/templates/block/block--inline-block--testimonial-on-image-background.html.twig
…image div in Testimonial.
Added functionality to set an aria-label on the background image div in Testimonial
- [JIRA ticket](https://asudev.jira.com/browse/WS2-2324)
> WS2-2324: Testimonial on Image Background: background image is missing alt text

- web/themes/webspark/renovation/src/components/quote-image-background/quote-image-background.twig
Prevent rendering of empty aria-label attribute using conditional in Twig
- [JIRA ticket](https://asudev.jira.com/browse/WS2-2324)
> WS2-2324: Add conditional to render aria-label only when it has content

- web/profiles/webspark/webspark/config/install/core.entity_form_display.block_content.gallery.default.yml
- web/profiles/webspark/webspark/webspark.install
Refactoring Image gallery form
- [JIRA ticket](https://asudev.jira.com/browse/WS2-1788)
1. Enter [Image gallery](https://pr-622-webspark-ci.ws.asu.edu/image-gallery)
2. Edit the layout
3. Edit the Image Gallery block
4. Inspect the "Note: All carousel images have to be the same aspect ratio." and verify that the `h3` tag had only the `note` 
6. Verify that the form matches the appearance of other forms.
> WS2-1788: Refactoring Image gallery form

- web/modules/webspark/asu_footer/src/Plugin/Block/AsuFooterBlock.php
Added description for media_library input on Footer block form
- [JIRA ticket](https://asudev.jira.com/browse/WS2-1746)
> WS2-1746: Added description for media_library input on Footer block form

- web/themes/webspark/renovation/src/components/cards/card-image-and-content.twig
- web/themes/webspark/renovation/templates/block/block--inline-block--card-image-and-content.html.twig
Added aria-label on card-image-and-content
- [JIRA ticket](https://asudev.jira.com/browse/WS2-2407)
> WS2-2407: Added aria-label on card-image-and-content

- features/bootstrap/FeatureContext.php
- features/ckeditor-buttons.feature
- features/pagination.feature
A few Behat tests were failing because they are too specific, so any small changes in content will break them. I update these particular tests to be more generic but still adequately test the desired functionality. Other tests will need these changes, but those will be addressed as they come up.
The pagination test still requires us to add a threshold, but is now more flexible and easier to match whatever the view setting is. The test will now skip the check if it is not needed.
- [JIRA ticket](https://asudev.jira.com/browse/WS2-2440)
> WS2-2440: Update outdated Behat tests

- pantheon.yml
- web/themes/webspark/renovation/src/components/cards/card-and-image-parallax.twig
- web/themes/webspark/renovation/src/components/cards/card-and-image.twig
- web/themes/webspark/renovation/templates/block/block--inline-block--card-and-image.html.twig
Added aria-label and alt for card-and-image.twig
- [JIRA ticket](https://asudev.jira.com/browse/WS2-2419)
> WS2-2419: Added aria-label and alt for card-and-image.twig

- web/modules/asu_modules/asu_brand/js/asu_brand.header.js
Removes unneeded jQuery load-in for header initialization.
1. Visit PR site and ensure the header loads.
2. Login. Make sure the header stays loaded.
3. Check the console log for errors related to the header JS initialization - specifically `Uncaught ReferenceError: jQuery is not defined`.
4. Clear the cache. Is the header still around?
If all those check out, this works as defined.
Bonus points, you could do a performance test using https://pagespeed.web.dev/ and comparing the PR site with our current sprint site and check to for improvements. Before this update:
Note: This isn't the only JS being loaded, so it's possible some other code is loading jQuery, if it shows up in the scan. But at least we've stopped requiring it for every instance of the header and reduced the likelihood of it …
> WS2-2466 remove jquery from header initialization script

- web/themes/webspark/renovation/templates/form/fieldset.html.twig
Removed div wrapper from fieldset.html.twig
- [JIRA ticket](https://asudev.jira.com/browse/WS2-2299)
> WS2-2299: Removed div wrapper from fieldset.html.twig

- upstream-configuration/patches.webspark.json
- upstream-configuration/patches/field_states_ui_3371927_mr_10.patch
- web/modules/webspark/webspark_webdir/src/Plugin/Field/FieldWidget/WebdirAddPeopleWidget.php
- web/modules/webspark/webspark_webdir/src/Plugin/Field/FieldWidget/WebdirAddWidget.php
- web/modules/webspark/webspark_webdir/src/Plugin/Field/FieldWidget/WebdirAsuriteWidget.php
- web/modules/webspark/webspark_webdir/src/Plugin/Field/FieldWidget/WebdirCampusWidget.php
- web/modules/webspark/webspark_webdir/src/Plugin/Field/FieldWidget/WebdirDepartmentsWidget.php
- web/modules/webspark/webspark_webdir/src/Plugin/Field/FieldWidget/WebdirEmployeeTypeWidget.php
- web/modules/webspark/webspark_webdir/src/Plugin/Field/FieldWidget/WebdirExpertiseWidget.php
- web/modules/webspark/webspark_webdir/src/Plugin/Field/FieldWidget/WebdirListWidget.php
Using Xdebug, I found that all of the other elements that used the field_states API had a `#field_parents` array in their field definition. So, I added that to all of our widgets, and it solved the problem. While I was in there, I added a couple of patches to make field_states_ui work better. They were my first attempt to fix things, but while they improved the overall experience, they didn't alleviate the notice messages regarding `#field_parents`. So, they are a little scope-creepy, but not too bad. We needed them anyway.
- [JIRA ticket](https://asudev.jira.com/browse/WS2-1329)
> WS2 1329: Layout Builder UI Notice - FIeld states UI notice in drupal log when adding a webdir block via layout builder

- upstream-configuration/composer.json
- web/profiles/webspark/webspark/webspark.info.yml
This PR updates the webspark version numbers to 2.15.0.
- [JIRA ticket](https://asudev.jira.com/browse/WS2-2507)
> WS2-2507: Update webspark version numbers

- .github/workflows/mono-package-split.yml
I discovered that the monorepo deployment didn't work when we released WS2.15.1. This should fix that problem.
> fix mono-package-split.yml

- web/themes/webspark/renovation/includes/form.inc
- web/themes/webspark/renovation/templates/form/form-element.html.twig
This PR improves accessibility by adding aria-describedby attributes to <input> and <textarea> elements. This allows screen readers (such as VoiceOver) to properly associate error messages with their respective form fields, enhancing the user experience for visually impaired users.
**Changes Implemented**
Added _aria-describedby_ in _hook_preprocess_input()_
Ensures that all <input> elements include an aria-describedby attribute referencing the corresponding error message container.
This helps screen readers announce validation errors when users navigate through form fields.
Example:
`<input name="email" aria-describedby="error-email">
`Added aria-describedby in hook_preprocess_textarea()
Similar to the input fields, this ensures <textarea> elements include the aria-describedby attribute …
> WS2-2307: Webform: confusing error message ARIA label for text fields

- web/themes/webspark/renovation/templates/form/form-element-label.html.twig
Removed the `title` attribute from the `span` that marks required fields in the form label Twig template.
- [JIRA ticket](https://asudev.jira.com/browse/WS2-2298)
> WS2-2298: Removed title from form label
