- README.md
See: https://asudev.jira.com/browse/WS2-1596
This PR updates the project README with documentation for the Webspark CI project.
> WS2-1596: Document the Build Tools workflow

- upstream-configuration/composer.json
- web/profiles/webspark/webspark/webspark.info.yml
Increment the release number.
Fixes update path from older versions.
> Increment release number to 2.10.1

- composer.lock
- upstream-configuration/composer.json
- web/modules/webspark/asu_footer/src/Plugin/Block/AsuFooterBlock.php
- web/themes/webspark/renovation/templates/block/asu-footer--footer-block.html.twig
Reverts ASUWebPlatforms/webspark-ci#133
> Revert "Ws2 1740: We need to update the Twitter Icon to the X logo in the footer"

- composer.lock
- upstream-configuration/composer.json
- web/modules/webspark/asu_footer/src/Plugin/Block/AsuFooterBlock.php
- web/themes/webspark/renovation/templates/block/asu-footer--footer-block.html.twig
Now that we have WS2-1754, this PR is ready for merging again. Sorry. I thought it would be more difficult to find a solution. 
¯\_(ツ)_/¯
This should probably be merged after WS2-1754, but as long as they both end up in the sprint deploy, I guess it doesn't matter too much.
> Retry WS2-1740

- composer.lock
- upstream-configuration/patches.webspark.json
- upstream-configuration/scripts/ComposerScripts.php
- web/profiles/webspark/webspark/config/install/fontawesome.settings.yml
- web/profiles/webspark/webspark/webspark.install
- web/themes/webspark/renovation/asuawesome-iconlist.yml
- web/themes/webspark/renovation/js/asuawesome.js
- web/themes/webspark/renovation/renovation.fontawesome.iconlist.yml
- web/themes/webspark/renovation/templates/system/html.html.twig
Sprint 45 includes updating the Drupal FontAwesome module to the dev branch. However, this causes Composer to throw an error if the code changes are accepted. This is because there is a mismatch with the patch we are applying (#3219579: Hidding font awesome additional settings). The Dev branch of the module fixes this issue, which makes the patch outdated. So, we need to remove the patch and adjust how we handle hiding the additional settings. The Dev branch handles this situation by creating a new permission. We just need to make sure that permission is not enabled for anyone except Administrators.
The other part of this ticket is that we need to get the ASUAwesome icons to be included in the FontAwesome Icon Picker Widget. We do this by slightly changing the approach of how we are …
> WS2-1773: Fix FontAwesome composer problem and add FontAwesome Icon Picker Widget support for ASUAwesome

- upstream-configuration/patches.webspark.json
Test new patches for Drupal core for the 2.11 release.
> Test new patches

- web/modules/webspark/webspark_blocks/webspark_blocks.install
Small refactor so that update 9020 does not load all the configs.
> Update some install hooks to prevent reloading all configs

- composer.lock
- upstream-configuration/patches.webspark.json
Missing lock file caused Composer Lock Updater to fail.
CKEditor patch https://www.drupal.org/project/drupal/issues/3097338#comment-14886712 caused patching to hang. Doesn't seem to be needed in 9.5.11. Removed.
> ws2 release add composer.lock, remove problem patch

- web/modules/webspark/webspark_blocks/js/anchor-menu.js
- web/modules/webspark/webspark_blocks/webspark_blocks.libraries.yml
Behavior that added anchor menu items needed to use once so it wouldn't "dupe up".
- [JIRA ticket](https://asudev.jira.com/browse/WS2-1772)
> WS2-1772 onceify anchor menu item append

- web/modules/webspark/webspark_blocks/js/anchor-menu.js
Added scrollspy functionality by adding correct attribute to body
- [JIRA ticket](https://asudev.jira.com/browse/UDS-1560?atlOrigin=eyJpIjoiMzIzZGZiYTI3OWY4NGMxZDkxY2RkY2M4NzQ3NWE3YWIiLCJwIjoiaiJ9)
> Add scrollspy functionality to anchor menu

- upstream-configuration/composer.json
- web/modules/webspark/webspark_blocks/webspark_blocks.install
- web/profiles/webspark/webspark/webspark.info.yml
update version numbers. avoid dupe full reverts for webspark_blocks configs.
> Prep 2 12 0

- web/profiles/webspark/webspark/webspark.info.yml
> update webspark profile .info file

- behat.yml
- composer.json
- composer.lock
- features/README.md
- features/anon-user.feature
- features/bootstrap/FeatureContext.php
- features/visit-homepage.feature
Add necessary files to run local Behat testing in the WebsparkCi site.
- [JIRA ticket](https://asudev.jira.com/browse/WS2-1812)
> Ws2 1812: Setup and Configure Behat testing for `webspark-ci`

- features/bootstrap/FeatureContext.php
- features/react-component-check.feature
Original PR from @tbutterf 
Description
I have included all of the tests mentioned in the ticket, but I have commented out the one for the component-cookie-consent because the cookie consent form and the Foresee thing mess up Behat tests. So, I turned them off, like we did on iSearch. I thought about adding some tests that check the cookie consent and then turn those two things off, and then turn them back on when the tests are done. But, that seems like a lot of work without checking in first. So, for the time being I just have it so that we need to go to /admin/config/asu_brand/settings and uncheck the two checkboxes before we run the tests locally.
Links
[JIRA ticket](https://asudev.jira.com/browse/WS2-1813)
> Ws2 1813: Test that UDS React components initialize successfully

- README.md
> WS2 Sprint 55

- web/modules/webspark/webspark_blocks/js/card-arrangement.js
> fix card arrangement bug

- web/themes/webspark/renovation/src/sass/layout-builder.scss
> Fix z-index issue for CKEditor links

- features/bootstrap/FeatureContext.php
- features/degree-listing.feature
- features/section-options.feature
JIRA ticket: https://asudev.jira.com/browse/WS2-1947
For behat tickets I usually don't allow the CI process to build a multidev, since it isn't testable that way. It needs to be tested locally in DDEV.
> WS2-1947: Behat testing for Degree Listing Page

- features/donut-chart.feature
Jira ticket: https://asudev.jira.com/browse/WS2-1948
> Ws2 1948: Behat testing for Donut Chart

- features/react-component-check.feature
Added new test for Anchor menu functionality
- [JIRA ticket](https://asudev.jira.com/browse/WS2-1946)
> WS2 1946 - Added new test for Anchor menu functionality

- features/footer.feature
Added footer test
- [JIRA ticket](https://asudev.jira.com/browse/WS2-1950)
> WS2-1950: Added new footer test

- web/themes/webspark/renovation/src/components/cards/card-and-image.twig
- web/themes/webspark/renovation/src/sass/helpers/_containers.scss
Originally opened by @juanmitriatti, but was accidentally closed prematurely
> WS2-1869: Added styles for align box to right in Card and Image block

- features/bootstrap/FeatureContext.php
- features/pagination.feature
- [JIRA ticket](https://asudev.jira.com/browse/WS2-1811)
> WS2 1811: Behat testing for pagination

- web/modules/webspark/asu_react_core/js/component-carousel-image-gallery.js
- web/themes/webspark/renovation/src/components/paragraphs/_paragraphs.scss
Changed maxWidth value in UDS call and added styles for li into glide
- [JIRA ticket](https://asudev.jira.com/browse/WS2-1657)
> WS2-1657: Image Gallery - What is the correct width?

- web/themes/webspark/renovation/src/components/block/image-block.twig
- web/themes/webspark/renovation/src/components/image/_images.scss
- web/themes/webspark/renovation/src/components/image/image.twig
- web/themes/webspark/renovation/templates/image/image.html.twig
Added classes and functionality to remove rounded image border
- [JIRA ticket](https://asudev.jira.com/browse/WS2-1834)
> WS2-1834: Media Library: Add cropped image round option

- features/video.feature
Add a new Behat test for the Video component.
- [JIRA ticket](https://asudev.jira.com/browse/WS2-1958)
- [ x ] Solution is documented on the Jira ticket
- [ x ] QA steps to verify have been included on the Jira ticket
- [ x ] No new PHP or JS errors
- [ x ] No accessibility issues are introduced with this update
> WS2-1958: Add a new Behat test for Video embeds

- features/react-component-check.feature
This PR simply removes a test that is no longer needed.
- [JIRA ticket](https://asudev.jira.com/browse/WS2-1964)
> WS2-1964: Removed Anchor Menu test

- .github/pull_request_template.md
Add PR template check for update hooks.
- [JIRA ticket](https://asudev.jira.com/browse/WS2-1670)
> WS2-1670 - Update PR template to check update hooks.

- web/themes/webspark/renovation/src/components/accordions/accordion.twig
Jerkiness of the Accordion transitions
Replicate UDS solution in the accordion twig template
- [JIRA ticket](https://asudev.jira.com/browse/WS2-1908)
> WS2-1908: Apply UDS accordion update to prevent jerkiness

- features/bootstrap/FeatureContext.php
- features/webform.feature
Added new test for Verify that users can view and interact with Webform
- [JIRA ticket](https://asudev.jira.com/browse/WS2-1960)
> WS2-1960: Behat testing Webform

- web/modules/webspark/asu_react_core/src/Utils/ReactComponentHelperFunctions.php
This PR applies a fix Travis came up with to resolve an issue with URLs being passed to React components.
- [JIRA ticket](https://asudev.jira.com/browse/WS2-2091)
> WS2-2091: Update string URI generation for some React components

- web/modules/webspark/webspark_blocks/config/install/field.storage.block_content.field_sub_heading_background.yml
- web/modules/webspark/webspark_blocks/webspark_blocks.install
Added new hero option to match the new mockup.
- [New mockup](https://xd.adobe.com/view/ff2c049b-410d-41bc-bcc4-9dc7711e04a7-aa7f/screen/6104fa75-e0de-4aaa-b190-0717669a14b2/specs/)
- [JIRA ticket](https://asudev.jira.com/browse/WS2-2026?atlOrigin=eyJpIjoiYTY1ZTU4NzNiM2IwNDZkM2ExYWZmZWFkMjA2ZWU4MTYiLCJwIjoiaiJ9)
> WS2-2026 - Added new hero option

- composer.json
- composer.lock
- upstream-configuration/composer.json
This PR moves the `drupal/imagick` module out of the root `composer.json` file and into `upstream-configuration/composer.json`.
- [JIRA ticket](https://asudev.jira.com/browse/WS2-2123)
> WS2-2123: Move Imagick module out of root composer file

- web/modules/webspark/webspark_webdir/js/webspark_webdir.js
Ended up hiding all filters via JavaScript when Custom Webdir sort is selected.
QA steps:
- Log in and navigate to /node/31/layout
- Click the pencil icon and click Configure on the block named "Departments"
- Toggle the "Default sort" dropdown from "Last name" to "Web directory customized sort" several times. 
- You should see all of the filters and the People list get hidden when the customized sort is selected. You should see the disclaimer text about filter settings not applying to the customized sort option. Also, the “Disable alphabetical filter” checkbox should get hidden. The selected values of all of these filters should be blanked out when they are being hidden. You can check this by noting something that has been selected, toggling to the customized sort option, and then using …
> WS2-1916: JSM - WS2 - Web Directory Block Department Defined Sort By (spa-webspark-2)

- web/themes/webspark/renovation/package.json
- web/themes/webspark/renovation/src/components/cards/_card-and-image-parallax.scss
- web/themes/webspark/renovation/templates/block/asu-footer--footer-block.html.twig
- web/themes/webspark/renovation/yarn.lock
This PR updates the Unity Bootstrap Theme to the most recent version, and brings over any other additional changes in scope.
- [JIRA ticket](https://asudev.jira.com/browse/WS2-2104)
> WS2-2104: Update Unity Bootstrap Theme

- web/modules/webspark/asu_degree_rfi/asu_degree_rfi.install
- web/modules/webspark/asu_degree_rfi/config/install/asu_degree_rfi.settings.yml
Previous version added settings yml that was overwriting values not included in it... removing that file and handling via update hook and install hook.
> WS2-2034 fix config handling for install and update

- features/bootstrap/FeatureContext.php
- features/pagination.feature
- features/react-component-check.feature
- features/sidebar-menu.feature
- features/webform.feature
This updates Behat tests to match some recent updates. 
Some things to note:
- Some of the changes that have needed to be made are because accordions are no longer collapsible. I want to verify that this is intentional. This is true for the accordions and also the sidebar-menu.
- The text-lists errors are a false-positive. I had forgotten to compile the theme locally.
- [JIRA ticket](https://asudev.jira.com/browse/WS2-2125)
> Ws2 2125: Update Behat tests to match current conditions

- web/modules/webspark/asu_react_core/js/component-card-arrangement.js
- web/modules/webspark/asu_react_core/src/ReactComponentCardArrangement.php
Fixed horizontal functionality in card arrangement
- [JIRA ticket](https://asudev.jira.com/browse/WS2-2065)
> WS2-2065: JSM - WS2 - Card Arrangement (Barrett Prospective)

- web/themes/webspark/renovation/templates/page/page.html.twig
> WS2-2141 tabindex for skipnav

- web/modules/webspark/webspark_ckeditor_plugins/css/websparkglobal.css
- web/themes/webspark/renovation/src/components/lists/_lists.scss
WS2-2136: Added new classes for uds-list p
- [JIRA ticket](https://asudev.jira.com/browse/WS2-2136)
> WS2-2136: PR - New Step Lists do not work as expected in CKEditor

- features/react-component-check.feature
> fix accordion test [skip ci]

- web/modules/webspark/webspark_blocks/js/anchor-menu.js
This PR removes unused code from the Anchor Menu. Leaving it there will just cause confusion.
- [JIRA ticket](https://asudev.jira.com/browse/WS2-1570)
> WS2-1570: Remove unused code from Anchor Menu

- web/themes/webspark/renovation/package.json
- web/themes/webspark/renovation/src/components/banners/banners.twig
- web/themes/webspark/renovation/src/components/buttons/button-cta.twig
- web/themes/webspark/renovation/src/components/headings/heading.twig
- web/themes/webspark/renovation/templates/field/field--block-content--field-heading--banner.html.twig
- web/themes/webspark/renovation/templates/field/field--block-content--field-heading.html.twig
- web/themes/webspark/renovation/yarn.lock
Changed banners.twig, button-cta.twig, field--block-content-field-heading.html.twig and heading.twig for accessibility
- [JIRA ticket](https://asudev.jira.com/browse/WS2-2194)
> WS2-2194: Changed banners.twig, button-cta.twig, field--block-content-field-heading.html.twig and heading.twig for accessibility

- web/themes/webspark/renovation/package.json
- web/themes/webspark/renovation/src/components/charts-and-graphs/donut.twig
- web/themes/webspark/renovation/yarn.lock
Upgraded unity-bootstrap-theme and refactoring donut.twig
- [JIRA ticket](https://asudev.jira.com/browse/WS2-2222)
> WS2-2222: Upgraded unity-bootstrap-theme and refactoring donut.twig

- web/modules/webspark/webspark_utility/src/Drush/Commands/WebsparkUtilityCommands.php
Just moving the code up to the top, and simplifying it a little.
> WS2-2269 add-on: move login check to beginning

- web/themes/webspark/renovation/src/components/heroes/heroes.twig
- web/themes/webspark/renovation/src/components/heroes/image-hero.twig
- web/themes/webspark/renovation/src/components/heroes/video-hero.twig
This PR brings in markup changes from components identified in the `check-element-changes` script.
> WS2-2291: Update hero markup from check-element-changes

- web/modules/webspark/asu_degree_rfi/asu_degree_rfi.libraries.yml
- web/modules/webspark/asu_degree_rfi/css/asu_degree_rfi.rfi.css
Fix hover styles on RFI buttons. Outdated custom CSS that wasn't needed. Able to remove the whole file.
- [JIRA ticket](https://asudev.jira.com/browse/WS2-2292)
> WS2-2293 remove unneeded and wrong rfi button styles

- web/modules/webspark/asu_degree_rfi/src/AsuDegreeRfiDataPotluckClient.php
- web/modules/webspark/asu_degree_rfi/src/Controller/AsuDegreePagesCreation.php
Needed to use `acadPlanMarketingDescription` to match Degree Search and component labels. Also had to work thorugh update to handle the multiple instances of the same parameter. Ended up being simple using an array and Query::build() form Guzzle.
- [JIRA ticket](https://asudev.jira.com/browse/WS2-2308)
> WS2-2308 use acadPlanMarketingDescription in admin UI

- composer.json
- composer.lock
- upstream-configuration/composer.json
- web/modules/webspark/webspark_module_views_pager/templates/asu-pager.html.twig
- web/profiles/webspark/webspark/webspark.info.yml
Drupal core moderately critical security update.
- [JIRA ticket](https://asudev.jira.com/browse/WS2-2439)
- Verify with Behat testing
- Verify with PR multidev site
> Ws2 2 14 1 hotfix

- web/themes/webspark/renovation/package.json
- web/themes/webspark/renovation/yarn.lock
Upgrade unity-bootstrap-theme
- [JIRA ticket](https://asudev.jira.com/browse/WS2-1756)
> WS2-1756: Upgrade unity-bootstrap-theme

- web/profiles/webspark/webspark/config/install/core.entity_form_display.block_content.image.default.yml
- web/profiles/webspark/webspark/config/install/core.entity_view_display.block_content.image.default.yml
- web/profiles/webspark/webspark/config/install/field.field.block_content.image.field_center_image.yml
- web/profiles/webspark/webspark/config/install/field.storage.block_content.field_center_image.yml
- web/profiles/webspark/webspark/config/install/field.storage.block_content.field_image_size.yml
- web/profiles/webspark/webspark/webspark.install
- web/themes/webspark/renovation/src/components/block/image-block.twig
- web/themes/webspark/renovation/templates/block/block--inline-block--image.html.twig
Added 75% option and center image functionality
- [JIRA ticket](https://asudev.jira.com/browse/WS2-1836)
> WS2-1836: Added 75% option and center image functionality

- README.md
- web/themes/webspark/renovation/src/sass/layout-builder.scss
Added style for resize layout builder form
- [JIRA ticket](https://asudev.jira.com/browse/WS2-1897)
> WS2-1897: Added style for resize layout builder form

- web/modules/webspark/webspark_webdir/config/install/field.field.block_content.web_directory.field_default_sort.yml
- web/modules/webspark/webspark_webdir/config/install/field.storage.block_content.field_default_sort.yml
- web/modules/webspark/webspark_webdir/js/list-field.js
- web/modules/webspark/webspark_webdir/js/webspark_webdir.js
- web/modules/webspark/webspark_webdir/webspark_webdir.install
- [JIRA ticket](https://asudev.jira.com/browse/WS2-2470)
> WS2-2470: Update default sort config

- web/themes/webspark/renovation/package.json
- web/themes/webspark/renovation/yarn.lock
- [JIRA ticket](https://asudev.jira.com/browse/WS2-2387)
> WS2-2387: Upgraded unity-bootstrap-theme

- web/modules/webspark/webspark_utility/config/install/field.storage.block_content.field_heading.yml
- web/profiles/webspark/webspark/config/install/core.entity_form_display.node.article.default.yml
- web/profiles/webspark/webspark/config/install/core.entity_view_display.node.article.default.yml
- web/profiles/webspark/webspark/config/install/core.entity_view_display.node.article.rss.yml
- web/profiles/webspark/webspark/config/install/core.entity_view_display.node.article.teaser.yml
This PR fixes the configs for 2.15 so new sites can be installed.
> FIX: fix configs for new installs

- pantheon.yml
This PR removes the unnecessary `pantheon.yml` file.
> Remove unused file
